version: '3.8'
services:
  unifloral:
    build: .
    image: unifloral
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - MUJOCO_GL=osmesa
      - PYOPENGL_PLATFORM=osmesa
      - DISPLAY=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash